name: Flow-CI-Honkit

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
env:
  USER_EMAIL: ${{secrets.USER_Ekkjk}}
  USER_NAME: ${{secrets.USER_NAME}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
        uses: monstar-lab-oss/honkit-ghpages-action@main
